package banquemisr.challenge05.presentation.screens.home

object MoviesScreenSemantics {

    const val MOVIES_SCREEN_ERROR = "MOVIES_SCREEN_ERROR"

    object MoviesListSemantics {
        const val MOVIES_FULL_LOADING_FOR_PLAYING_MOVIES_TAG = "MOVIES_FULL_LOADING_FOR_PLAYING_MOVIES_TAG"
        const val MOVIES_FULL_LOADING_FOR_UPCOMING_MOVIES_TAG = "MOVIES_FULL_LOADING_FOR_UPCOMING_MOVIES_TAG"
        const val MOVIES_FULL_LOADING_FOR_POPULAR_MOVIES_TAG = "MOVIES_FULL_LOADING_FOR_POPULAR_MOVIES_TAG"
        const val MOVIES_PAGING_LOADING_FOR_UPCOMING_MOVIES_TAG = "MOVIES_PAGING_LOADING_FOR_UPCOMING_MOVIES_TAG"
        const val UPCOMING_MOVIES_LIST_TAG = "UPCOMING_MOVIES_LIST_TAG"

    }
}